name: plz
description: A universal package manager
dependencies:
  yaml: "^2.1.4"
  args: "^0.13.2"
  node_io:
    git: https://github.com/dglogik/node_io.dart.git
dev_dependencies:
  test: "^0.12.4+7"
  dart_coveralls: "^0.4.0"